### ISSUE TITLE
Flicker on IOS when transitioning cards

### ISSUE THREAD

**Issue by ryanthegiantlion** [Ryanthegiantlion/react-native-tinder-swipe#1]
Turns out there is a flicker on IOS when transitioning between cards (haven't reproduced on android yet)

This makes me sad :-(

**Comment by ryanthegiantlion** [comment]
@musnit If you could test this for me that would be great!

**Comment by ryanthegiantlion** [comment]
Btw, it seems that 

```
key={this.state.currentPerson.name}
```

was the critical change.

I only have a vague idea of how react rendering works but I guess it gives a hint to the react diff algorithm and probably stops a 'repaint' in this case.

**Comment by Lloydza** [comment]
@Ryanthegiantlion why are there bugs in this code??? I thought I trained you better than this.

**Comment by musnit** [comment]
seems fixed :)
